[package]
name = "dnschk"
version = "0.1.0"
authors = ["Richard Alvarez <rawalvarez731@gmail.com>"]
license = "MIT"
build = "build.rs"

[lib]
name = "dnschk"
crate-type = ["dylib"]

[build-dependencies]
neon-build = "0.1.22"

[dependencies]
neon = "0.1.22"