"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.regenerate = void 0;

var _fs = require("fs");

var _util = require("util");

var _gulp = _interopRequireDefault(require("gulp"));

var _gulpTap = _interopRequireDefault(require("gulp-tap"));

var _del = _interopRequireDefault(require("del"));

var _fancyLog = _interopRequireDefault(require("fancy-log"));

var _parseGitignore = _interopRequireDefault(require("parse-gitignore"));

var _core = require("@babel/core");

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

const paths = {};
const readFileAsync = (0, _util.promisify)(_fs.readFile);
paths.flowTypedGitIgnore = 'flow-typed/.gitignore';
paths.configs = 'config';
paths.regenTargets = [`${paths.configs}/gulpfile.js`];
const CLI_BANNER = `/**
 * !!! DO NOT EDIT THIS FILE DIRECTLY !!!
 * ! This file has been generated automatically. See the *.babel.js version of
 * ! this file to make permanent modifications (in config/)
 */\n\n`;

const cleanTypes = async () => {
  const targets = (0, _parseGitignore.default)((await readFileAsync(paths.flowTypedGitIgnore)));
  (0, _fancyLog.default)(`Deleting targets: "${targets.join('" "')}"`);
  (0, _del.default)(targets);
};

cleanTypes.description = 'Resets the flow-types directory to a pristine state';

_gulp.default.task('clean-types', cleanTypes);

const regenerate = () => {
  (0, _fancyLog.default)(`Regenerating targets: "${paths.regenTargets.join('" "')}"`);
  process.env.BABEL_ENV = 'generator';
  return _gulp.default.src(paths.regenTargets).pipe((0, _gulpTap.default)(file => file.contents = Buffer.from((0, _core.transformSync)(`${CLI_BANNER}${file.contents.toString()}`).code))).pipe(_gulp.default.dest('.'));
};

exports.regenerate = regenerate;
regenerate.description = 'Invokes babel on the files in config, transpiling them into their project root versions';